name: CI

on: [ push, pull_request ]

defaults:
  run:
    shell: bash

jobs:
  # Checks for standalone usage (without R) 
  ubuntu-standalone-check:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Compile standalone programs
      run: cd standalone && make -f nii_info.make
    
    - name: Test standalone programs
      run: |
        standalone/nii_info inst/extdata/example.nii.gz
        standalone/nii2_info inst/extdata/example.nii.gz
  
  # Standalone check on Windows
  windows-standalone-check:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    
    # Set up Developer Command Prompt to see MSVC commands
    - uses: ilammy/msvc-dev-cmd@v1
    
    - name: Compile standalone programs
      shell: pwsh
      run: cd standalone; nmake /f nii_info.nmake
    
    - name: Test standalone programs
      shell: pwsh
      run: |
        standalone/nii_info inst/extdata/example.nii.gz
        standalone/nii2_info inst/extdata/example.nii.gz
