name: CI

on: [ push, pull_request ]

defaults:
  run:
    shell: bash

jobs:
  # Checks for standalone usage (without R) 
  standalone-check:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest ]
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Compile standalone programs
      run: cd standalone && make
    
    - name: Test standalone programs
      run: |
        standalone/nii_info inst/extdata/example.nii.gz
        standalone/nii2_info inst/extdata/example.nii.gz
